require('dotenv').config();
const assert=require('assert'),knexLib=require('knex'),actions=require('../extensions/server_connect/modules/communicationEmail'),security=require('../extensions/server_connect/modules/metipathSecurity')._test,cfg=require('../app/modules/connections/db.json').options.connection;
(async()=>{const knex=knexLib({client:'mysql2',connection:cfg}),trx=await knex.transaction();try{
  const actor=await trx('tbl_user_tenant_roles as utr').join('tbl_role_permissions as rp','rp.roleId','utr.roleId').join('tbl_permissions as p','p.id','rp.permissionId').join('tbl_tenant_modules as tm','tm.tenantId','utr.tenantId').join('tbl_modules as mod','mod.id','tm.moduleId').where({'p.permissionCode':'email.communications.manage','utr.isActive':1,'mod.moduleCode':'EMAIL_INTEGRATION'}).whereIn('tm.status',['ACTIVE','TRIAL']).first('utr.userId','utr.tenantId');assert(actor,'A Phase G manager is required');
  const connection=await trx('tbl_email_connections').where({tenantId:actor.tenantId,isActive:1}).whereNotNull('nylasGrantId').first(),workflow=await trx('tbl_workflows').where({tenantId:actor.tenantId}).first();assert(connection&&workflow,'A connected mailbox and event are required');const mailbox=security.decrypt({ciphertext:connection.mailboxAddressCiphertext,iv:connection.mailboxAddressIv,authTag:connection.mailboxAddressAuthTag,keyVersion:connection.keyVersion,encryptionVersion:1},actor.tenantId,'email.mailbox'),tag=Date.now(),thread=`phase-g-manual-thread-${tag}`,base={grant_id:connection.nylasGrantId,from:[{email:'assign-test@example.test'}],to:[{email:mailbox}],date:Math.floor(Date.now()/1000),body:'Ambiguous assignment test',attachments:[]};
  const first=await actions._test.ingest(trx,connection,{...base,id:`phase-g-manual-${tag}`,thread_id:thread,subject:'Please review'});assert(!first.matched,'message starts unmatched');let statusCode=200;const app={req:{session:{USER_ID:actor.userId,TENANT_ID:actor.tenantId},body:{communicationId:first.communicationId,workflowId:workflow.id},query:{}},res:{headersSent:false,status(code){statusCode=code;return this}},getDbConnection(){return trx}};const assigned=await actions.assign.call(app);assert(assigned.success&&Number(assigned.workflowId)===Number(workflow.id),'one-click assignment succeeds');assert(await trx('tbl_communication_thread_links').where({tenantId:actor.tenantId,threadId:(await trx('tbl_communications').where({id:first.communicationId}).first()).threadId,entityType:'workflow',entityId:workflow.id}).first(),'provider thread is linked');assert(!await trx('tbl_communications').where({id:first.communicationId,status:'pending_review'}).first(),'assigned email leaves unmatched queue');
  const reply=await actions._test.ingest(trx,connection,{...base,id:`phase-g-manual-reply-${tag}`,thread_id:thread,subject:'Reply without event reference'});assert(reply.matched&&Number(reply.workflowId)===Number(workflow.id),'subsequent thread message inherits event');
  app.req.query={q:String(workflow.referenceCode||workflow.workflowName).slice(0,20)};const search=await actions.searchRecords.call(app);assert(search.records.some(r=>Number(r.id)===Number(workflow.id)),'event search returns the selected event');assert.strictEqual(statusCode,200);console.log('Phase G assignment UI backend: 7 assertions passed');
}finally{await trx.rollback();await knex.destroy()}})().catch(e=>{console.error(e);process.exit(1)});
