const assert=require('assert'),knex=require('knex'),moduleUnderTest=require('../extensions/server_connect/modules/commercialTerms');
const db=knex(require('../app/modules/connections/db.json').options);
function app(trx,tenantId,userId,request={}){return{req:{session:{TENANT_ID:tenantId,USER_ID:userId},query:request.query||{},body:request.body||{}},res:{headersSent:false,status(){return this}},getDbConnection:()=>trx}}
(async()=>{let assertions=0;await db.transaction(async trx=>{const admin=await trx('tbl_user_tenant_roles as utr').join('tbl_role_permissions as rp','rp.roleId','utr.roleId').join('tbl_permissions as p','p.id','rp.permissionId').where({'utr.tenantId':6,'utr.isActive':1,'p.permissionCode':'commercial.manage'}).first('utr.userId'),workflow=await trx('tbl_workflows').where({tenantId:6}).whereNotNull('workflowTypeId').first(),foreign=await trx('tbl_workflows').whereNot({tenantId:6}).first();assert(admin&&workflow&&foreign);
  const result=await moduleUnderTest.get.call(app(trx,6,admin.userId,{query:{workflowId:workflow.id}}));assert(result.sections.length>0);assertions++;
  await assert.rejects(()=>moduleUnderTest.get.call(app(trx,6,admin.userId,{query:{workflowId:foreign.id}})),/Workflow not found/);assertions++;
  const viewerMembership=await trx('tbl_user_tenant_roles').where({tenantId:6,userId:32,isActive:1}).first(),viewPermission=await trx('tbl_permissions').where({permissionCode:'commercial.view'}).first();if(viewerMembership&&viewPermission){await trx('tbl_role_permissions').insert({roleId:viewerMembership.roleId,permissionId:viewPermission.id}).onConflict(['roleId','permissionId']).ignore();await moduleUnderTest.get.call(app(trx,6,32,{query:{workflowId:workflow.id}}));await assert.rejects(()=>moduleUnderTest.saveAgreement.call(app(trx,6,32,{body:{workflowId:workflow.id,currencyCode:'GBP'}})),/access denied/i);assertions++}
  const price=await moduleUnderTest.saveChild.call(app(trx,6,admin.userId,{body:{workflowId:workflow.id,kind:'price',description:'Test price',amount:'25.50',quantity:'10'}}));assert(price.id);assertions++;
  await moduleUnderTest.saveChild.call(app(trx,6,admin.userId,{body:{workflowId:workflow.id,kind:'price',id:price.id,description:'Updated test price',amount:'30.00',quantity:'12'}}));assert.equal(Number((await trx('tbl_commercial_price_items').where({id:price.id}).first()).amount),30);assertions++;
  await moduleUnderTest.removeChild.call(app(trx,6,admin.userId,{body:{workflowId:workflow.id,kind:'price',id:price.id}}));assert.equal((await trx('tbl_commercial_price_items').where({id:price.id}).first()).isActive,0);assertions++;
  const definition=result.definitions[0],responsibilityOption=result.options.find(x=>x.optionGroup==='responsibility'),responsibility=await moduleUnderTest.saveChild.call(app(trx,6,admin.userId,{body:{workflowId:workflow.id,kind:'responsibility',definitionId:definition.id,responsibilityOptionId:responsibilityOption.id,amount:'45',percentage:'4.2',quantity:'2',notes:'Configured fields only'}}));assert(responsibility.id);assertions++;
  const adjustment=await moduleUnderTest.saveChild.call(app(trx,6,admin.userId,{body:{workflowId:workflow.id,kind:'adjustment',description:'Test deduction',calculationType:'percentage',percentage:'4.2'}})),schedule=await moduleUnderTest.saveChild.call(app(trx,6,admin.userId,{body:{workflowId:workflow.id,kind:'schedule',description:'Completion',amount:'1000',dueDate:'2027-01-01',status:'planned'}}));assert(adjustment.id&&schedule.id);assertions++;
  assert.equal(moduleUnderTest._test.num('75.25',0,100),75.25);assertions++;assert.throws(()=>moduleUnderTest._test.num('75%',0,100),/Invalid numeric/);assertions++;
  const eventSections=result.sections.map(x=>x.sectionKey);assert(eventSections.includes('prices')&&!eventSections.includes('payment_schedule'));assertions++;
  const typeIds=await trx('tbl_workflow_types').insert({tenantId:6,typeName:'Grant configuration test',description:'Transactional test only',colour:'#198754',sortOrder:999,isActive:1}),grantTypeId=typeIds[0],grantSections=['agreement','responsibilities','payment_schedule','additional'],allSections=['agreement','prices','responsibilities','adjustments','payment_terms','payment_schedule','additional'];for(let i=0;i<allSections.length;i++)await trx('tbl_commercial_workflow_configs').insert({tenantId:6,workflowTypeId:grantTypeId,sectionKey:allSections[i],heading:allSections[i].replace('_',' '),isEnabled:grantSections.includes(allSections[i]),sortOrder:(i+1)*10});for(const [i,label]of['Staff Costs','Equipment','Professional Fees','Capital Costs','Match Funding','In-kind Contribution'].entries())await trx('tbl_commercial_item_definitions').insert({tenantId:6,workflowTypeId:grantTypeId,sectionKey:'responsibilities',itemKey:label.toLowerCase().replace(/[^a-z0-9]+/g,'_'),label,allowAmount:1,allowPercentage:label==='Match Funding',allowQuantity:0,allowNotes:1,sortOrder:(i+1)*10,isActive:1});const config=await moduleUnderTest.configuration.call(app(trx,6,admin.userId,{query:{workflowTypeId:grantTypeId}}));assert.deepEqual(config.sections.filter(x=>x.isEnabled).map(x=>x.sectionKey),grantSections);assert(config.definitions.some(x=>x.label==='Professional Fees')&&!config.definitions.some(x=>x.label==='Technicians'));assertions++;
  throw Object.assign(new Error('ROLLBACK_TEST'),{rollback:true});
}).catch(e=>{if(!e.rollback)throw e});console.log(`Commercial terms engine: ${assertions} assertions passed`);await db.destroy()})().catch(async e=>{console.error(e);await db.destroy();process.exit(1)});
