require('dotenv').config();
const assert=require('assert'),crypto=require('crypto'),knexLib=require('knex'),actions=require('../extensions/server_connect/modules/communicationEmail'),cfg=require('../app/modules/connections/db.json').options.connection;
(async()=>{const knex=knexLib({client:'mysql2',connection:cfg}),trx=await knex.transaction();try{
  const connection=await trx('tbl_email_connections').whereNotNull('nylasGrantId').first(),workflow=connection&&await trx('tbl_workflows').where({tenantId:connection.tenantId}).whereNotNull('referenceCode').first();assert(connection&&workflow,'A connected mailbox and referenced workflow are required');
  const sec=require('../extensions/server_connect/modules/metipathSecurity')._test,mailbox=sec.decrypt({ciphertext:connection.mailboxAddressCiphertext,iv:connection.mailboxAddressIv,authTag:connection.mailboxAddressAuthTag,keyVersion:connection.keyVersion,encryptionVersion:1},connection.tenantId,'email.mailbox'),tag=Date.now();
  const base={grant_id:connection.nylasGrantId,from:[{email:'phase-g-sender@example.test'}],to:[{email:mailbox}],cc:[],bcc:[],date:Math.floor(Date.now()/1000),body:'Phase G deterministic matching test',snippet:'test',attachments:[]};
  const exact=await actions._test.ingest(trx,connection,{...base,id:`phase-g-exact-${tag}`,thread_id:`phase-g-thread-exact-${tag}`,subject:`Re ${workflow.referenceCode}`});assert(exact.matched&&Number(exact.workflowId)===Number(workflow.id),'exact reference must auto-link');
  const ambiguous=await actions._test.ingest(trx,connection,{...base,id:`phase-g-ambiguous-${tag}`,thread_id:`phase-g-thread-ambiguous-${tag}`,subject:'General question'});assert(!ambiguous.matched,'ambiguous incoming must remain unmatched');const ambiguousRow=await trx('tbl_communications').where({id:ambiguous.communicationId}).first();assert.strictEqual(ambiguousRow.status,'pending_review');
  const outgoing=await actions._test.ingest(trx,connection,{...base,id:`phase-g-outgoing-${tag}`,thread_id:`phase-g-thread-outgoing-${tag}`,from:[{email:mailbox}],to:[{email:'outside@example.test'}],subject:'Unrelated outgoing'});assert(outgoing.ignored,'unmatched outgoing must be ignored');
  const reply=await actions._test.ingest(trx,connection,{...base,id:`phase-g-reply-${tag}`,thread_id:`phase-g-thread-exact-${tag}`,subject:'Thread reply without reference'});assert(reply.matched&&Number(reply.workflowId)===Number(workflow.id),'linked thread reply must auto-link');
  assert.strictEqual(actions._test.plain('<p>Hello <img src="https://tracker.test/x">world</p>'),'Hello world');
  process.env.NYLAS_WEBHOOK_SECRET='phase-g-secret';const raw='{"id":"phase-g"}',signature=crypto.createHmac('sha256','phase-g-secret').update(raw).digest('hex'),valid=await actions._test.verifyWebhook({req:{rawBody:raw,headers:{'x-nylas-signature':signature}}});assert(valid,'valid webhook HMAC must pass');const invalid=await actions._test.verifyWebhook({req:{rawBody:raw+'x',headers:{'x-nylas-signature':signature}}});assert(!invalid,'modified webhook body must fail');
  console.log('Phase G communications: 8 assertions passed');
}finally{await trx.rollback();await knex.destroy()}})().catch(e=>{console.error(e);process.exit(1)});
