// Idempotent example configuration. The engine remains generic; tenants may rename or duplicate this form.
exports.up = async function up(k) {
  if (!await k.schema.hasTable('tbl_form_templates')) throw new Error('Apply 20260808_configurable_forms.js first.');
  const tenants = await k('tbl_tenants').select('id');
  for (const tenant of tenants) {
    let form = await k('tbl_form_templates').where({tenantId:tenant.id,formType:'record',formName:'Event Information',version:1}).first();
    if (!form) { const ids=await k('tbl_form_templates').insert({tenantId:tenant.id,formType:'record',formName:'Event Information',formDescription:'Configurable Record information for event workflows.',version:1,status:'published',isActive:1,isSystemTemplate:1,publishedDate:k.fn.now(),createdDate:k.fn.now(),modifiedDate:k.fn.now()}); form={id:ids[0]}; }
    const sectionDefs=[['commercial_terms','Commercial Terms','commercial',10],['ticketing','Ticketing','commercial',20],['costs_responsibilities','Costs & Responsibilities','commercial',30],['technical','Technical','details',40],['hospitality','Hospitality','details',50]];
    const sections={};
    for(const [sectionKey,sectionName,displayLocation,displayOrder] of sectionDefs){await k('tbl_form_sections').insert({tenantId:tenant.id,formTemplateId:form.id,sectionKey,sectionName,displayLocation,displayOrder,isCollapsible:0,isDefaultExpanded:1,isActive:1,createdDate:k.fn.now(),modifiedDate:k.fn.now()}).onConflict(['tenantId','formTemplateId','sectionKey']).merge({sectionName,displayLocation,displayOrder,isActive:1});sections[sectionKey]=(await k('tbl_form_sections').where({tenantId:tenant.id,formTemplateId:form.id,sectionKey}).first()).id;}
    const fields=[
      ['commercial_terms','contract_type','Contract Type','dropdown',10,6,1],['commercial_terms','venue_hire_fee','Venue Hire Fee','currency',20,6,0],['commercial_terms','guarantee','Guarantee','currency',30,4,0],['commercial_terms','venue_percentage','Venue Percentage','percentage',40,4,0],['commercial_terms','promoter_percentage','Promoter Percentage','percentage',50,4,0],['commercial_terms','settlement_notes','Settlement Notes','long_text',60,12,0],
      ['ticketing','ticket_prices','Ticket Prices','repeatable_table',10,12,0],['ticketing','complimentary_allocation','Complimentary Allocation','number',20,4,0],['ticketing','ticketing_notes','Ticketing Notes','long_text',30,12,0],
      ['costs_responsibilities','technicians_paid_by','Technicians Paid By','dropdown',10,6,0],['costs_responsibilities','technician_charge','Technician Charge','currency',20,6,0],['costs_responsibilities','marketing_paid_by','Marketing Paid By','dropdown',30,6,0],['costs_responsibilities','security_paid_by','Security Paid By','dropdown',40,6,0],['costs_responsibilities','ticketing_fees_paid_by','Ticketing Fees Paid By','dropdown',50,6,0],
      ['technical','technical_requirements','Technical Requirements','long_text',10,12,0],['technical','venue_technicians_required','Venue Technicians Required','yes_no',20,6,0],['technical','number_of_venue_technicians','Number of Venue Technicians','number',30,6,0],['technical','technical_notes','Technical Notes','long_text',40,12,0],
      ['hospitality','hospitality_required','Hospitality Required','yes_no',10,6,0],['hospitality','hospitality_notes','Hospitality Notes','long_text',20,12,0]
    ];
    const fieldIds={};
    for(const [sectionKey,fieldKey,fieldLabel,fieldType,displayOrder,columnWidth,isRequired] of fields){await k('tbl_form_fields').insert({tenantId:tenant.id,formTemplateId:form.id,formSectionId:sections[sectionKey],fieldKey,fieldLabel,fieldType,displayOrder,columnWidth,isRequired,isReadOnly:0,isHidden:0,validationJson:JSON.stringify(fieldType==='percentage'?{min:0,max:100,precision:2}:{}),settingsJson:JSON.stringify({}),isActive:1,createdDate:k.fn.now(),modifiedDate:k.fn.now()}).onConflict(['tenantId','formTemplateId','fieldKey']).merge({fieldLabel,fieldType,displayOrder,columnWidth,isActive:1});fieldIds[fieldKey]=(await k('tbl_form_fields').where({tenantId:tenant.id,formTemplateId:form.id,fieldKey}).first()).id;}
    const addOptions=async(fieldKey,labels)=>{for(let i=0;i<labels.length;i++){const [optionValue,optionLabel]=Array.isArray(labels[i])?labels[i]:[labels[i].toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,''),labels[i]];await k('tbl_form_field_options').insert({tenantId:tenant.id,formFieldId:fieldIds[fieldKey],optionValue,optionLabel,displayOrder:(i+1)*10,isActive:1,createdDate:k.fn.now(),modifiedDate:k.fn.now()}).onConflict(['tenantId','formFieldId','optionValue']).merge({optionLabel,displayOrder:(i+1)*10,isActive:1});}};
    await addOptions('contract_type',[['straight_hire','Straight Venue Hire'],['revenue_split','Revenue Split'],['guarantee','Guarantee'],['guarantee_split','Guarantee + Revenue Split'],['other','Other']]);
    for(const f of ['technicians_paid_by','marketing_paid_by','security_paid_by'])await addOptions(f,['Venue','Promoter','Included','Shared','Other']);
    await addOptions('ticketing_fees_paid_by',['Venue','Promoter','Customer','Included','Shared','Other']);
    const addCondition=async(target,controller,operator,comparisonValue,conditionAction)=>{const exists=await k('tbl_form_field_conditions').where({tenantId:tenant.id,formFieldId:fieldIds[target],controllingFieldId:fieldIds[controller],operator,comparisonValue,conditionAction}).first();if(!exists)await k('tbl_form_field_conditions').insert({tenantId:tenant.id,formFieldId:fieldIds[target],controllingFieldId:fieldIds[controller],operator,comparisonValue,conditionAction,createdDate:k.fn.now(),modifiedDate:k.fn.now()});};
    for(const target of ['venue_percentage','promoter_percentage']){await addCondition(target,'contract_type','equals','revenue_split','show');await addCondition(target,'contract_type','equals','guarantee_split','show');}
    await addCondition('guarantee','contract_type','equals','guarantee','show');await addCondition('guarantee','contract_type','equals','guarantee_split','show');
    for(const target of ['number_of_venue_technicians','technician_charge'])await addCondition(target,'venue_technicians_required','equals','1','show');
    await addCondition('hospitality_notes','hospitality_required','equals','1','show');
    const cols=[['ticket_type','Ticket Type','text',1,10],['price','Price','currency',1,20],['allocation','Allocation','number',0,30],['complimentary_allocation','Complimentary Allocation','number',0,40]];
    for(const [columnKey,columnLabel,columnType,isRequired,displayOrder] of cols)await k('tbl_form_repeatable_columns').insert({tenantId:tenant.id,formFieldId:fieldIds.ticket_prices,columnKey,columnLabel,columnType,isRequired,displayOrder,settingsJson:JSON.stringify({}),isActive:1}).onConflict(['tenantId','formFieldId','columnKey']).merge({columnLabel,columnType,isRequired,displayOrder,isActive:1});
    if(await k.schema.hasColumn('tbl_workflow_templates','recordFormTemplateId'))await k('tbl_workflow_templates').where({tenantId:tenant.id}).whereNotIn('status',['archived','inactive']).whereNull('recordFormTemplateId').update({recordFormTemplateId:form.id});
  }
};
exports.down = async function down(){ /* Seed is intentionally retained; archive it through Forms administration. */ };
