exports.up=async function(k){
  if(!await k.schema.hasTable('tbl_commercial_workflow_configs'))await k.schema.createTable('tbl_commercial_workflow_configs',t=>{t.increments('id');t.integer('tenantId').unsigned().notNullable();t.integer('workflowTypeId').unsigned().notNullable();t.string('sectionKey',50).notNullable();t.string('heading',160);t.boolean('isEnabled').notNullable().defaultTo(true);t.integer('sortOrder').notNullable().defaultTo(100);t.timestamps(true,true);t.unique(['tenantId','workflowTypeId','sectionKey'],'uq_commercial_section');t.index(['tenantId','workflowTypeId','isEnabled'],'idx_commercial_section');});
  if(!await k.schema.hasTable('tbl_commercial_option_definitions'))await k.schema.createTable('tbl_commercial_option_definitions',t=>{t.increments('id');t.integer('tenantId').unsigned().notNullable();t.integer('workflowTypeId').unsigned().notNullable();t.string('optionGroup',40).notNullable();t.string('optionKey',80).notNullable();t.string('label',160).notNullable();t.json('fieldRulesJson');t.integer('sortOrder').defaultTo(100);t.boolean('isActive').defaultTo(true);t.timestamps(true,true);t.unique(['tenantId','workflowTypeId','optionGroup','optionKey'],'uq_commercial_option');});
  if(!await k.schema.hasTable('tbl_commercial_item_definitions'))await k.schema.createTable('tbl_commercial_item_definitions',t=>{t.increments('id');t.integer('tenantId').unsigned().notNullable();t.integer('workflowTypeId').unsigned().notNullable();t.string('sectionKey',50).notNullable();t.string('itemKey',100).notNullable();t.string('label',160).notNullable();t.boolean('askResponsibility').defaultTo(true);t.boolean('allowAmount').defaultTo(true);t.boolean('allowPercentage').defaultTo(false);t.boolean('allowQuantity').defaultTo(false);t.boolean('allowVat').defaultTo(false);t.boolean('allowNotes').defaultTo(true);t.boolean('isRequired').defaultTo(false);t.string('defaultOptionKey',80);t.integer('sortOrder').defaultTo(100);t.boolean('isActive').defaultTo(true);t.timestamps(true,true);t.unique(['tenantId','workflowTypeId','sectionKey','itemKey'],'uq_commercial_item_definition');});
  if(!await k.schema.hasTable('tbl_commercial_records'))await k.schema.createTable('tbl_commercial_records',t=>{t.increments('id');t.integer('tenantId').unsigned().notNullable();t.integer('workflowId').unsigned().notNullable();t.integer('agreementTypeId').unsigned();t.string('currencyCode',3).notNullable().defaultTo('GBP');t.decimal('fixedAmount',14,2);t.decimal('minimumAmount',14,2);t.decimal('guaranteeAmount',14,2);t.decimal('organisationPercentage',7,4);t.decimal('counterpartyPercentage',7,4);t.decimal('maximumAmount',14,2);t.string('settlementBasis',500);t.string('vatTreatment',120);t.boolean('depositRequired').defaultTo(false);t.decimal('depositAmount',14,2);t.decimal('depositPercentage',7,4);t.date('depositDueDate');t.date('balanceDueDate');t.string('paymentTerms',500);t.string('settlementPeriod',160);t.string('settlementMethod',160);t.text('cancellationTerms');t.text('notes');t.integer('createdByUserId').unsigned();t.integer('modifiedByUserId').unsigned();t.dateTime('modifiedDate').notNullable().defaultTo(k.fn.now());t.timestamps(true,true);t.unique(['tenantId','workflowId'],'uq_commercial_record');});
  const child=async(name,extra)=>{if(await k.schema.hasTable(name))return;await k.schema.createTable(name,t=>{t.increments('id');t.integer('tenantId').unsigned().notNullable();t.integer('workflowId').unsigned().notNullable();extra(t);t.integer('sortOrder').defaultTo(100);t.boolean('isActive').defaultTo(true);t.integer('createdByUserId').unsigned();t.integer('modifiedByUserId').unsigned();t.dateTime('modifiedDate').notNullable().defaultTo(k.fn.now());t.timestamps(true,true);t.index(['tenantId','workflowId','isActive','sortOrder'],`idx_${name.replace('tbl_commercial_','comm_')}`);});};
  await child('tbl_commercial_price_items',t=>{t.string('description',160).notNullable();t.decimal('amount',14,2);t.decimal('quantity',14,3);t.string('vatTreatment',120);t.text('notes');});
  await child('tbl_commercial_responsibility_items',t=>{t.integer('definitionId').unsigned();t.string('description',160);t.integer('responsibilityOptionId').unsigned();t.string('basis',80);t.decimal('amount',14,2);t.decimal('percentage',7,4);t.decimal('quantity',14,3);t.string('vatTreatment',120);t.string('settlementTreatment',160);t.text('notes');});
  await child('tbl_commercial_adjustments',t=>{t.string('description',160).notNullable();t.string('calculationType',40).notNullable();t.decimal('amount',14,2);t.decimal('percentage',7,4);t.decimal('unitAmount',14,2);t.text('notes');});
  await child('tbl_commercial_payment_schedule',t=>{t.string('description',160).notNullable();t.decimal('amount',14,2);t.decimal('percentage',7,4);t.date('dueDate');t.string('triggerText',255);t.string('status',40);t.text('notes');});
  await child('tbl_commercial_custom_values',t=>{t.integer('templateCustomFieldId').unsigned();t.string('fieldKey',120).notNullable();t.text('valueText');t.decimal('valueNumber',18,4);t.dateTime('valueDate');t.boolean('valueBoolean');});
  await k.raw("INSERT INTO tbl_permissions(permissionCode,permissionKey,permissionName,permissionDescription,permissionScope,permissionGroup,isSensitive,isAssignable,description,isActive) VALUES ('commercial.configure','commercial.configure','Configure commercial terms','Configure commercial or funding sections and definitions.','tenant','commercial',1,1,'Configure workflow-type commercial terms.',1) ON DUPLICATE KEY UPDATE permissionName=VALUES(permissionName),isActive=1");
  await k.raw("INSERT IGNORE INTO tbl_role_permissions(roleId,permissionId) SELECT r.id,p.id FROM tbl_roles r JOIN tbl_permissions p ON p.permissionCode='commercial.configure' WHERE r.roleKey IN ('owner','admin')");
  const sections=[['agreement','Agreement',10],['prices','Price Items',20],['responsibilities','Costs & Responsibilities',30],['adjustments','Adjustments',40],['payment_terms','Payment / Settlement Terms',50],['payment_schedule','Payment Schedule',60],['additional','Additional Terms',70]];
  const types=await k('tbl_workflow_types').select('id','tenantId','typeName');for(const wt of types){for(const [key,label,sort]of sections)await k('tbl_commercial_workflow_configs').insert({tenantId:wt.tenantId,workflowTypeId:wt.id,sectionKey:key,heading:label,isEnabled:key!=='payment_schedule',sortOrder:sort}).onConflict(['tenantId','workflowTypeId','sectionKey']).ignore();const agreements=['Straight Venue Hire','Fixed Fee','Guarantee','Box Office Split','Guarantee + Box Office Split','Contra / No Fee','Internal','Other'];for(let i=0;i<agreements.length;i++){const label=agreements[i],key=label.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');await k('tbl_commercial_option_definitions').insert({tenantId:wt.tenantId,workflowTypeId:wt.id,optionGroup:'agreement_type',optionKey:key,label,fieldRulesJson:JSON.stringify(key.includes('split')?{organisationPercentage:true,counterpartyPercentage:true,settlementBasis:true}:key.includes('hire')?{fixedAmount:true,vatTreatment:true,paymentTerms:true}:key.includes('guarantee')?{guaranteeAmount:true,settlementBasis:true}:{notes:true}),sortOrder:(i+1)*10}).onConflict(['tenantId','workflowTypeId','optionGroup','optionKey']).ignore()}const responsibilities=['Organisation pays','Counterparty pays','Shared','Included','Recharged','Deducted from settlement','Paid directly','Third party pays','In-kind','Not applicable','Other'];for(let i=0;i<responsibilities.length;i++){const label=responsibilities[i],key=label.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');await k('tbl_commercial_option_definitions').insert({tenantId:wt.tenantId,workflowTypeId:wt.id,optionGroup:'responsibility',optionKey:key,label,sortOrder:(i+1)*10}).onConflict(['tenantId','workflowTypeId','optionGroup','optionKey']).ignore()}const items=['Technicians','Security','Marketing','PRS / Rights','Equipment Hire','Accommodation','Travel','Hospitality / Rider','Catering','Cleaning','Other'];for(let i=0;i<items.length;i++){const label=items[i],key=label.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');await k('tbl_commercial_item_definitions').insert({tenantId:wt.tenantId,workflowTypeId:wt.id,sectionKey:'responsibilities',itemKey:key,label,allowAmount:true,allowPercentage:key==='prs_rights'||key==='marketing',allowQuantity:key==='technicians',allowVat:true,sortOrder:(i+1)*10}).onConflict(['tenantId','workflowTypeId','sectionKey','itemKey']).ignore()}}
  await k.raw("INSERT INTO tbl_tenant_terminology(tenantId,termKey,singularLabel,pluralLabel) SELECT id,'commercial.tab_name','Commercial','Commercial' FROM tbl_tenants ON DUPLICATE KEY UPDATE termKey=termKey");
  await k.raw("INSERT INTO tbl_tenant_terminology(tenantId,termKey,singularLabel,pluralLabel) SELECT id,'commercial.section_name','Commercial Terms','Commercial Terms' FROM tbl_tenants ON DUPLICATE KEY UPDATE termKey=termKey");
  if(await k.schema.hasTable('tbl_workflow_commercial_details'))await k.raw("INSERT INTO tbl_commercial_records(tenantId,workflowId,currencyCode,maximumAmount,vatTreatment,notes,createdByUserId,modifiedByUserId,created_at,updated_at) SELECT tenantId,workflowId,currencyCode,salesTarget,taxNotes,CONCAT_WS('\\n',notes,CASE WHEN onSaleDateTime IS NOT NULL THEN CONCAT('Legacy available-from date: ',onSaleDateTime) END,CASE WHEN capacity IS NOT NULL THEN CONCAT('Legacy capacity / quantity: ',capacity) END),createdByUserId,modifiedByUserId,createdDate,modifiedDate FROM tbl_workflow_commercial_details ON DUPLICATE KEY UPDATE workflowId=VALUES(workflowId)");
  if(await k.schema.hasTable('tbl_workflow_price_entries'))await k.raw("INSERT INTO tbl_commercial_price_items(tenantId,workflowId,description,amount,notes,sortOrder,isActive,createdByUserId,modifiedByUserId,created_at,updated_at) SELECT tenantId,workflowId,priceLabel,amount,CONCAT_WS(' - ',eligibility,CASE WHEN calculationType<>'fixed_amount' THEN CONCAT('Legacy calculation: ',REPLACE(calculationType,'_',' ')) END),displayOrder,isActive,createdByUserId,modifiedByUserId,createdDate,modifiedDate FROM tbl_workflow_price_entries old WHERE NOT EXISTS(SELECT 1 FROM tbl_commercial_price_items n WHERE n.tenantId=old.tenantId AND n.workflowId=old.workflowId AND n.description=old.priceLabel AND n.created_at=old.createdDate)");
  await k('tbl_commercial_option_definitions').where({optionGroup:'agreement_type',optionKey:'straight_venue_hire'}).update({fieldRulesJson:JSON.stringify({fixedAmount:true,vatTreatment:true,paymentTerms:true})});
  await k('tbl_commercial_option_definitions').where({optionGroup:'agreement_type',optionKey:'fixed_fee'}).update({fieldRulesJson:JSON.stringify({fixedAmount:true,vatTreatment:true,paymentTerms:true})});
  await k('tbl_commercial_option_definitions').where({optionGroup:'agreement_type',optionKey:'guarantee'}).update({fieldRulesJson:JSON.stringify({guaranteeAmount:true,settlementBasis:true})});
  await k('tbl_commercial_option_definitions').where({optionGroup:'agreement_type',optionKey:'box_office_split'}).update({fieldRulesJson:JSON.stringify({organisationPercentage:true,counterpartyPercentage:true,settlementBasis:true})});
  await k('tbl_commercial_option_definitions').where({optionGroup:'agreement_type',optionKey:'guarantee_box_office_split'}).update({fieldRulesJson:JSON.stringify({guaranteeAmount:true,organisationPercentage:true,counterpartyPercentage:true,settlementBasis:true})});
  await k('tbl_commercial_option_definitions').where({optionGroup:'agreement_type',optionKey:'minimum_guarantee'}).update({fieldRulesJson:JSON.stringify({minimumAmount:true,settlementBasis:true})});
};
exports.down=async function(k){for(const n of ['tbl_commercial_custom_values','tbl_commercial_payment_schedule','tbl_commercial_adjustments','tbl_commercial_responsibility_items','tbl_commercial_price_items','tbl_commercial_records','tbl_commercial_item_definitions','tbl_commercial_option_definitions','tbl_commercial_workflow_configs'])await k.schema.dropTableIfExists(n)};
