const slug=v=>String(v).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
exports.up=async function up(k){
  const tenants=await k('tbl_tenants').select('id');
  for(const tenant of tenants){
    const owner=(await k('tbl_user_tenants').where({tenantId:tenant.id,isActive:1,membershipStatus:'active'}).first('userId'))?.userId||null;
    const ensureTemplate=async(name,description,isDefault)=>{let row=await k('tbl_workflow_templates').where({tenantId:tenant.id,templateKey:slug(name)}).first();if(!row){const ids=await k('tbl_workflow_templates').insert({tenantId:tenant.id,templateName:name,templateKey:slug(name),description,versionNumber:1,status:'published',isDefault,createdByUserId:owner});row={id:ids[0]}}return row.id};
    const ensurePhase=async(templateId,name,order)=>{let row=await k('tbl_template_stages').where({tenantId:tenant.id,templateId,stageName:name}).first();if(!row){const ids=await k('tbl_template_stages').insert({tenantId:tenant.id,templateId,stageName:name,sortOrder:order,status:'active',requiresProgressionApproval:0,allowManualOverride:1});row={id:ids[0]}}return row.id};
    const ensureQuestion=async(templateId,phaseId,q)=>{let row=await k('tbl_template_tasks').where({tenantId:tenant.id,templateId,templateStageId:phaseId,taskName:q.text}).first();const values={description:q.help||null,sortOrder:q.order,priority:'normal',status:'active',isRequired:q.required?1:0,responseRequired:1,responseType:q.type,answerType:q.type,showStartDate:q.start?1:0,showDeadline:q.deadline?1:0,showFinishDate:q.finish?1:0,allowNotes:q.notes?1:0,attachmentRequirement:q.attachment||'none',defaultAnswerValue:q.type==='task_status'?'not_started':null,defaultOwnerType:'unassigned',createdByUserId:owner,modifiedByUserId:owner};if(!row){const ids=await k('tbl_template_tasks').insert({tenantId:tenant.id,templateId,templateStageId:phaseId,taskName:q.text,...values});row={id:ids[0]}}else await k('tbl_template_tasks').where({id:row.id,tenantId:tenant.id}).update(values);for(const [i,label]of(q.options||[]).entries())await k('tbl_template_task_options').insert({tenantId:tenant.id,templateTaskId:row.id,optionValue:slug(label).replace(/-/g,'_'),optionLabel:label,displayOrder:(i+1)*10,isActive:1,createdByUserId:owner,modifiedByUserId:owner}).onConflict(['tenantId','templateTaskId','optionValue']).merge({optionLabel:label,displayOrder:(i+1)*10,isActive:1});};
    const standard=await ensureTemplate('Standard Theatre Show','Full theatre show task questions.',1),venue=await ensureTemplate('Venue Hire','Simpler venue-hire task questions.',0);
    const standardDefs={Enquiry:[{order:10,text:'Has the enquiry been acknowledged?',type:'yes_no',required:1,deadline:1,notes:1},{order:20,text:'Current enquiry status',type:'task_status',required:1,deadline:1}],Contract:[{order:10,text:'Has the contract been issued?',type:'yes_no',required:1,deadline:1,notes:1},{order:20,text:'Has the signed contract been received?',type:'yes_no',required:1,deadline:1,notes:1,attachment:'optional'}],Marketing:[{order:10,text:'Which marketing materials have been received?',type:'checkbox_multi',notes:1,options:['Artwork','Copy','Production Images','Video','Press Release']},{order:20,text:'Marketing approval status',type:'dropdown_single',required:1,options:['Awaiting Material','Under Review','Approved','Changes Required']}],Technical:[{order:10,text:'Technical arrangement',type:'radio',required:1,notes:1,options:['Standard Venue Setup','Enhanced Venue Setup','Touring Production','Other']},{order:20,text:'Technical requirements / comments',type:'text_long'}],'Event Delivery':[{order:10,text:'Event delivery status',type:'task_status',required:1,start:1,deadline:1,finish:1}]};
    let phaseOrder=10;for(const [name,questions]of Object.entries(standardDefs)){const phase=await ensurePhase(standard,name,phaseOrder);for(const q of questions)await ensureQuestion(standard,phase,q);phaseOrder+=10}
    const hireDefs={Enquiry:[{order:10,text:'Has the hire enquiry been acknowledged?',type:'yes_no',required:1,deadline:1,notes:1}],Contract:[{order:10,text:'Hire agreement status',type:'dropdown_single',required:1,options:['Draft','Issued','Signed','Cancelled']},{order:20,text:'Has the deposit been received?',type:'yes_no',required:1,deadline:1}],Delivery:[{order:10,text:'Venue handover notes',type:'text_long',notes:1},{order:20,text:'Hire completion status',type:'task_status',required:1,start:1,deadline:1,finish:1}]};
    phaseOrder=10;for(const [name,questions]of Object.entries(hireDefs)){const phase=await ensurePhase(venue,name,phaseOrder);for(const q of questions)await ensureQuestion(venue,phase,q);phaseOrder+=10}
  }
};
exports.down=async()=>{};
