const crypto=require('crypto'),security=require('./metipathSecurity')._test,nylas=require('./nylasEmailAdapter');
const MODULE='EMAIL_INTEGRATION';
function fail(app,status,message){if(app.res&&!app.res.headersSent)app.res.status(status);throw Object.assign(new Error(message),{status})}
function plain(value){return String(value||'').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#39;/g,"'").replace(/&quot;/gi,'"').replace(/\s+/g,' ').trim()}
function enc(value,tenantId,context){if(value===undefined||value===null||value==='')return null;return security.encrypt(typeof value==='string'?value:JSON.stringify(value),tenantId,context)}
function dec(row,prefix,tenantId,context){if(!row[`${prefix}Ciphertext`])return'';return security.decrypt({ciphertext:row[`${prefix}Ciphertext`],iv:row[`${prefix}Iv`],authTag:row[`${prefix}AuthTag`],keyVersion:row.keyVersion,encryptionVersion:row.encryptionVersion||1},tenantId,context)}
async function permission(db,tenantId,userId,code){return!!await db('tbl_user_tenant_roles as utr').join('tbl_roles as r','r.id','utr.roleId').join('tbl_role_permissions as rp','rp.roleId','r.id').join('tbl_permissions as p','p.id','rp.permissionId').where({'utr.tenantId':tenantId,'utr.userId':userId,'utr.isActive':1,'r.isActive':1,'p.permissionCode':code,'p.isActive':1}).first('rp.id')}
async function context(app,code='email.communications.view'){const tenantId=Number(app.req.session?.TENANT_ID),userId=Number(app.req.session?.USER_ID),db=app.getDbConnection('db');if(!tenantId||!userId)fail(app,401,'Authentication required.');const member=await db('tbl_user_tenants').where({tenantId,userId,isActive:1,membershipStatus:'active'}).first();if(!member)fail(app,403,'Tenant access denied.');const enabled=await db('tbl_tenant_modules as tm').join('tbl_modules as m','m.id','tm.moduleId').where({'tm.tenantId':tenantId,'m.moduleCode':MODULE,'m.isActive':1}).whereIn('tm.status',['ACTIVE','TRIAL']).first('tm.id');if(!enabled)fail(app,403,'Email Integration is not enabled.');if(!await permission(db,tenantId,userId,code))fail(app,403,'Communication access denied.');return{tenantId,userId,db,member}}
async function record(c,app,id){const workflow=await c.db('tbl_workflows').where({id:Number(id)||0,tenantId:c.tenantId}).first();if(!workflow)fail(app,404,'Record not found.');return workflow}
async function mailboxAllowed(c,app,row){if(row.isSensitive&&!await permission(c.db,c.tenantId,c.userId,'email.communications.sensitive'))fail(app,403,'Sensitive mailbox access denied.');if(row.accessMode==='team'&&row.owningTeamId){const admin=await permission(c.db,c.tenantId,c.userId,'email.communications.manage'),team=await c.db('tbl_team_members as tm').join('tbl_user_tenants as ut','ut.id','tm.userTenantId').where({'tm.tenantId':c.tenantId,'tm.teamId':row.owningTeamId,'tm.isActive':1,'ut.userId':c.userId,'ut.isActive':1}).first('tm.id');if(!admin&&!team)fail(app,403,'Mailbox team access denied.')}}
function people(value){return(Array.isArray(value)?value:[]).map(p=>({name:String(p.name||''),email:String(p.email||'').toLowerCase()})).filter(p=>p.email)}
async function audit(db,c,action,entityId,summary){await db('tbl_activity_log').insert({tenantId:c.tenantId,userId:c.userId||null,entityType:'communication',entityId,actionType:action,summary,createdDate:db.fn.now()})}
async function participantRows(db,tenantId,communicationId,type,list){for(const p of people(list)){const email=enc(p.email,tenantId,'communication.participant.email'),name=enc(p.name,tenantId,'communication.participant.name');await db('tbl_communication_participants').insert({tenantId,communicationId,participantType:type,emailCiphertext:email.ciphertext,emailIv:email.iv,emailAuthTag:email.authTag,emailHash:security.searchHash(p.email,tenantId,'communication.participant.email','email'),nameCiphertext:name?.ciphertext||null,nameIv:name?.iv||null,nameAuthTag:name?.authTag||null,keyVersion:email.keyVersion})}}
async function ingest(db,connection,message){const tenantId=connection.tenantId,mailbox=security.decrypt({ciphertext:connection.mailboxAddressCiphertext,iv:connection.mailboxAddressIv,authTag:connection.mailboxAddressAuthTag,keyVersion:connection.keyVersion,encryptionVersion:1},tenantId,'email.mailbox'),from=people(message.from),to=people(message.to),cc=people(message.cc),bcc=people(message.bcc),direction=from.some(p=>p.email===mailbox.toLowerCase())?'outgoing':'incoming',threadExternal=String(message.thread_id||message.id),existingThread=await db('tbl_communication_threads').where({tenantId,sourceConnectionId:connection.id,externalThreadId:threadExternal}).first(),threadLinks=existingThread?await db('tbl_communication_thread_links').where({tenantId,threadId:existingThread.id,entityType:'workflow'}):[],body=plain(message.body||message.snippet),subject=String(message.subject||'(No subject)'),haystack=`${subject}\n${body}`.toLowerCase();let workflow=null,match='unmatched',reason=null;
  if(threadLinks.length===1){workflow=await db('tbl_workflows').where({tenantId,id:threadLinks[0].entityId}).first();match=workflow?'linked':'unmatched';reason='linked_thread'}
  if(!workflow){const workflows=await db('tbl_workflows').where({tenantId}).whereNotNull('referenceCode').select('id','referenceCode');const exact=workflows.filter(w=>w.referenceCode&&haystack.includes(String(w.referenceCode).toLowerCase()));if(exact.length===1){workflow=exact[0];match='linked';reason='exact_reference'}}
  if(direction==='outgoing'&&!workflow)return{ignored:true,reason:'unmatched_outgoing'};
  let thread=existingThread;if(!thread){const ids=await db('tbl_communication_threads').insert({tenantId,sourceType:'email',sourceConnectionId:connection.id,externalThreadId:threadExternal,status:'observed',createdDate:db.fn.now(),modifiedDate:db.fn.now()});thread={id:ids[0]}}
  const fields={},values=[['subject',subject,'communication.subject'],['bodyText',body,'communication.body_text'],['sender',from,'communication.sender'],['recipients',to,'communication.recipients'],['cc',cc,'communication.cc'],['bcc',bcc,'communication.bcc']];let keyVersion=1;for(const [prefix,value,ctx]of values){const encrypted=enc(value,tenantId,ctx);if(encrypted){fields[`${prefix}Ciphertext`]=encrypted.ciphertext;fields[`${prefix}Iv`]=encrypted.iv;fields[`${prefix}AuthTag`]=encrypted.authTag;keyVersion=encrypted.keyVersion}}
  const ids=await db('tbl_communications').insert({tenantId,communicationType:'email',direction,sourceType:'nylas',sourceConnectionId:connection.id,threadId:thread.id,occurredDate:new Date((Number(message.date)||Math.floor(Date.now()/1000))*1000),matchStatus:match,status:match==='linked'?'matched':'pending_review',matchedDate:workflow?db.fn.now():null,isForwarded:/^(fw|fwd):/i.test(subject)||/forwarded message/i.test(body),...fields,encryptionVersion:1,keyVersion,createdDate:db.fn.now(),modifiedDate:db.fn.now()}),communicationId=ids[0];await db('tbl_communication_email_metadata').insert({tenantId,communicationId,emailConnectionId:connection.id,nylasMessageId:String(message.id),keyVersion,createdDate:db.fn.now()});
  await participantRows(db,tenantId,communicationId,'from',from);await participantRows(db,tenantId,communicationId,'to',to);await participantRows(db,tenantId,communicationId,'cc',cc);await participantRows(db,tenantId,communicationId,'bcc',bcc);
  for(const a of(message.attachments||[]).filter(a=>!a.is_inline)){const filename=enc(String(a.filename||'Attachment'),tenantId,'communication.attachment.filename');await db('tbl_communication_attachment_metadata').insert({tenantId,communicationId,providerAttachmentId:String(a.id||''),fileNameCiphertext:filename?.ciphertext,fileNameIv:filename?.iv,fileNameAuthTag:filename?.authTag,keyVersion:filename?.keyVersion||1,mimeType:String(a.content_type||'').slice(0,255),fileSize:Number(a.size)||null,status:'metadata_only',createdDate:db.fn.now()})}
  if(workflow){await db('tbl_communication_links').insert({tenantId,communicationId,entityType:'workflow',entityId:workflow.id,relationshipType:reason,createdDate:db.fn.now()}).onConflict(['communicationId','entityType','entityId']).ignore();await db('tbl_communication_thread_links').insert({tenantId,threadId:thread.id,entityType:'workflow',entityId:workflow.id,relationshipType:reason,createdDate:db.fn.now()}).onConflict(['threadId','entityType','entityId']).ignore()}
  else{const emails=[...from,...to,...cc].map(p=>p.email),candidates=await db('tbl_workflow_contacts as wc').join('tbl_contacts as c','c.id','wc.contactId').join('tbl_workflows as w','w.id','wc.workflowId').where({'wc.tenantId':tenantId,'w.tenantId':tenantId}).whereIn(db.raw('LOWER(c.email)'),emails).distinct('w.id');for(const candidate of candidates)await db('tbl_communication_match_suggestions').insert({tenantId,communicationId,entityType:'workflow',entityId:candidate.id,reasonCode:'known_contact',confidence:candidates.length===1?0.8:0.6,createdDate:db.fn.now()}).onConflict(['communicationId','entityType','entityId']).ignore()}
  return{communicationId,matched:!!workflow,workflowId:workflow?.id||null}}
async function verifyWebhook(app){const secret=process.env.NYLAS_WEBHOOK_SECRET,signature=String(app.req.headers?.['x-nylas-signature']||'');if(!secret||!signature)return false;const expected=crypto.createHmac('sha256',secret).update(String(app.req.rawBody||'')).digest('hex'),a=Buffer.from(expected),b=Buffer.from(signature);return a.length===b.length&&crypto.timingSafeEqual(a,b)}
module.exports={
 async syncMailbox(){const c=await context(this,'email.communications.manage'),id=Number(this.req.body?.emailConnectionId),connection=await c.db('tbl_email_connections').where({id,tenantId:c.tenantId,isActive:1}).whereIn('connectionStatus',['connected','active']).first();if(!connection)fail(this,404,'Connected mailbox not found.');const response=await nylas.listMessages(connection.nylasGrantId,{limit:25,fields:'standard'}),messages=response.data||[];let processed=0,skipped=0;for(const message of messages){const exists=await c.db('tbl_communication_email_metadata').where({emailConnectionId:id,nylasMessageId:String(message.id)}).first('id');if(exists){skipped++;continue}let full=message;if(!message.body){const detail=await nylas.getMessage(connection.nylasGrantId,message.id);full=detail.data||detail}await ingest(c.db,connection,full);processed++}await c.db('tbl_email_connections').where({id,tenantId:c.tenantId}).update({lastSuccessfulSyncDate:c.db.fn.now(),modifiedDate:c.db.fn.now()});await audit(c.db,c,'MAILBOX_MANUAL_SYNC',id,`Recent mailbox processing completed: ${processed} processed, ${skipped} already known.`);return{success:true,processed,skipped}},
 async webhook(){if(this.req.method==='GET'){const challenge=String(this.req.query?.challenge||'');if(!challenge)fail(this,400,'Challenge required.');this.res.type('text/plain').send(challenge);return{}}if(!await verifyWebhook(this))fail(this,401,'Invalid webhook signature.');const payload=this.req.body||{},eventId=String(payload.id||''),eventType=String(payload.type||''),object=payload.data?.object||{};if(!eventId||!eventType)fail(this,400,'Invalid webhook payload.');const db=this.getDbConnection('db'),existing=await db('tbl_email_webhook_events').where({provider:'nylas',externalEventId:eventId}).first();if(existing)return{accepted:true,duplicate:true};await db('tbl_email_webhook_events').insert({provider:'nylas',externalEventId:eventId,eventType,grantIdHash:object.grant_id?crypto.createHash('sha256').update(String(object.grant_id)).digest('hex'):null,status:'processing',createdDate:db.fn.now(),modifiedDate:db.fn.now()});try{if(eventType.startsWith('message.created')){const connection=await db('tbl_email_connections').where({nylasGrantId:object.grant_id,isActive:1}).first();if(connection){let message=object;if(!message.body||eventType.includes('truncated')){const response=await nylas.getMessage(connection.nylasGrantId,object.id);message=response.data||response}await ingest(db,connection,message);await db('tbl_email_connections').where({id:connection.id}).update({lastWebhookDate:db.fn.now(),lastSuccessfulSyncDate:db.fn.now(),modifiedDate:db.fn.now()})}}await db('tbl_email_webhook_events').where({provider:'nylas',externalEventId:eventId}).update({status:'processed',processedDate:db.fn.now(),modifiedDate:db.fn.now()});return{accepted:true}}catch(e){await db('tbl_email_webhook_events').where({provider:'nylas',externalEventId:eventId}).update({status:'failed',errorCode:String(e.category||e.code||'PROCESSING_FAILED').slice(0,100),modifiedDate:db.fn.now()});fail(this,503,'Webhook processing temporarily failed.')}},
 async recordList(){const c=await context(this),workflow=await record(c,this,this.req.query?.workflowId),rows=await c.db('tbl_communications as comm').join('tbl_communication_links as link','link.communicationId','comm.id').join('tbl_email_connections as ec','ec.id','comm.sourceConnectionId').leftJoin('tbl_communication_email_metadata as em','em.communicationId','comm.id').where({'comm.tenantId':c.tenantId,'link.tenantId':c.tenantId,'link.entityType':'workflow','link.entityId':workflow.id}).whereNull('comm.deletedDate').orderBy('comm.occurredDate','desc').select('comm.*','ec.providerDisplayName','ec.mailboxAddressCiphertext','ec.mailboxAddressIv','ec.mailboxAddressAuthTag','ec.keyVersion as mailboxKeyVersion','ec.isSensitive','ec.accessMode','ec.owningTeamId','em.nylasMessageId');const out=[];for(const row of rows){await mailboxAllowed(c,this,row);out.push({id:row.id,direction:row.direction,date:row.occurredDate,subject:dec(row,'subject',c.tenantId,'communication.subject'),sender:JSON.parse(dec(row,'sender',c.tenantId,'communication.sender')||'[]'),recipients:JSON.parse(dec(row,'recipients',c.tenantId,'communication.recipients')||'[]'),sourceMailbox:security.decrypt({ciphertext:row.mailboxAddressCiphertext,iv:row.mailboxAddressIv,authTag:row.mailboxAddressAuthTag,keyVersion:row.mailboxKeyVersion,encryptionVersion:1},c.tenantId,'email.mailbox'),provider:row.providerDisplayName,hasAttachments:!!await c.db('tbl_communication_attachment_metadata').where({tenantId:c.tenantId,communicationId:row.id}).first('id'),threadId:row.threadId})}return{communications:out}},
 async preview(){const c=await context(this),id=Number(this.req.query?.id),row=await c.db('tbl_communications as comm').join('tbl_communication_links as link','link.communicationId','comm.id').join('tbl_email_connections as ec','ec.id','comm.sourceConnectionId').where({'comm.id':id,'comm.tenantId':c.tenantId,'link.tenantId':c.tenantId,'link.entityType':'workflow','link.entityId':Number(this.req.query?.workflowId)||0}).first('comm.*','ec.isSensitive','ec.accessMode','ec.owningTeamId');if(!row)fail(this,404,'Communication not found.');await record(c,this,this.req.query?.workflowId);await mailboxAllowed(c,this,row);return{preview:plain(dec(row,'bodyText',c.tenantId,'communication.body_text')).slice(0,500)}},
 async unmatched(){const c=await context(this,'email.communications.manage'),rows=await c.db('tbl_communications as comm').join('tbl_email_connections as ec','ec.id','comm.sourceConnectionId').where({'comm.tenantId':c.tenantId,'comm.direction':'incoming','comm.matchStatus':'unmatched','comm.status':'pending_review'}).orderBy('comm.occurredDate','desc').select('comm.*','ec.providerDisplayName','ec.mailboxAddressCiphertext','ec.mailboxAddressIv','ec.mailboxAddressAuthTag','ec.isSensitive','ec.accessMode','ec.owningTeamId');const out=[];for(const row of rows){await mailboxAllowed(c,this,row);const suggestions=await c.db('tbl_communication_match_suggestions as s').join('tbl_workflows as w','w.id','s.entityId').where({'s.tenantId':c.tenantId,'s.communicationId':row.id,'s.entityType':'workflow','s.status':'suggested'}).orderBy('s.confidence','desc').select('w.id','w.referenceCode','w.workflowName','s.reasonCode','s.confidence');out.push({id:row.id,date:row.occurredDate,subject:dec(row,'subject',c.tenantId,'communication.subject'),sender:JSON.parse(dec(row,'sender',c.tenantId,'communication.sender')||'[]'),preview:plain(dec(row,'bodyText',c.tenantId,'communication.body_text')).slice(0,500),provider:row.providerDisplayName,suggestions})}return{communications:out}},
 async searchRecords(){const c=await context(this,'email.communications.manage'),term=String(this.req.query?.q||'').trim().slice(0,100);if(term.length<2)return{records:[]};const records=await c.db('tbl_workflows').where({tenantId:c.tenantId}).where(q=>q.where('referenceCode','like',`%${term}%`).orWhere('workflowName','like',`%${term}%`)).orderBy('startDate','desc').limit(20).select('id','referenceCode','workflowName','startDate');return{records}},
 async assign(){const c=await context(this,'email.communications.manage'),communicationId=Number(this.req.body?.communicationId),workflow=await record(c,this,this.req.body?.workflowId),comm=await c.db('tbl_communications').where({id:communicationId,tenantId:c.tenantId}).first();if(!comm)fail(this,404,'Communication not found.');await c.db.transaction(async trx=>{await trx('tbl_communication_links').insert({tenantId:c.tenantId,communicationId,entityType:'workflow',entityId:workflow.id,relationshipType:'manual',createdByUserId:c.userId,createdDate:trx.fn.now()}).onConflict(['communicationId','entityType','entityId']).ignore();if(comm.threadId)await trx('tbl_communication_thread_links').insert({tenantId:c.tenantId,threadId:comm.threadId,entityType:'workflow',entityId:workflow.id,relationshipType:'manual',createdByUserId:c.userId,createdDate:trx.fn.now()}).onConflict(['threadId','entityType','entityId']).ignore();await trx('tbl_communications').where({id:communicationId,tenantId:c.tenantId}).update({matchStatus:'linked',status:'matched',matchedByUserId:c.userId,matchedDate:trx.fn.now(),modifiedDate:trx.fn.now()});await trx('tbl_communication_match_suggestions').where({tenantId:c.tenantId,communicationId}).update({status:'resolved'})});await audit(c.db,c,'EMAIL_MANUALLY_LINKED',communicationId,'Email manually linked to a record.');return{success:true}},
 async ignore(){const c=await context(this,'email.communications.manage'),id=Number(this.req.body?.communicationId),updated=await c.db('tbl_communications').where({id,tenantId:c.tenantId,direction:'incoming'}).update({matchStatus:'ignored',status:'ignored',modifiedDate:c.db.fn.now()});if(!updated)fail(this,404,'Communication not found.');await audit(c.db,c,'EMAIL_MARKED_IRRELEVANT',id,'Email marked not relevant to Metipath.');return{success:true}},
 _test:{plain,verifyWebhook,ingest}
};
