const MODULE='COMMERCIAL_DETAILS';
function fail(app,status,message){if(app.res&&!app.res.headersSent)app.res.status(status);throw Object.assign(new Error(message),{status})}
async function hasPermission(db,tenantId,userId,code){return!!await db('tbl_user_tenant_roles as utr').join('tbl_roles as r','r.id','utr.roleId').join('tbl_role_permissions as rp','rp.roleId','r.id').join('tbl_permissions as p','p.id','rp.permissionId').where({'utr.tenantId':tenantId,'utr.userId':userId,'utr.isActive':1,'r.isActive':1,'p.permissionCode':code,'p.isActive':1}).first('rp.id')}
async function context(app,code='commercial.view'){const tenantId=Number(app.req.session?.TENANT_ID),userId=Number(app.req.session?.USER_ID),db=app.getDbConnection('db');if(!tenantId||!userId)fail(app,401,'Authentication required.');if(!await db('tbl_user_tenants').where({tenantId,userId,isActive:1,membershipStatus:'active'}).first())fail(app,403,'Tenant access denied.');if(!await db('tbl_tenant_modules as tm').join('tbl_modules as m','m.id','tm.moduleId').where({'tm.tenantId':tenantId,'m.moduleCode':MODULE,'m.isActive':1}).whereIn('tm.status',['ACTIVE','TRIAL']).first())fail(app,403,'Commercial terms are not enabled.');if(!await hasPermission(db,tenantId,userId,code)&&!(code==='commercial.edit'&&await hasPermission(db,tenantId,userId,'commercial.manage')))fail(app,403,'Commercial terms access denied.');return{tenantId,userId,db}}
async function workflow(c,app,id){const row=await c.db('tbl_workflows').where({id:Number(id)||0,tenantId:c.tenantId}).first();if(!row)fail(app,404,'Workflow not found.');if(row.workflowTypeId)await ensureSections(c.db,c.tenantId,row.workflowTypeId);return row}
const num=(v,min=0,max=999999999999)=>{if(v===null||v===undefined||v==='')return null;const n=Number(v);if(!Number.isFinite(n)||n<min||n>max)throw Object.assign(new Error('Invalid numeric value.'),{status:422});return n};
function rules(app,value){try{const parsed=JSON.parse(String(value||'{}'));if(!parsed||Array.isArray(parsed)||typeof parsed!=='object')fail(app,422,'Conditional rules must be a JSON object.');return JSON.stringify(parsed)}catch(error){if(error.status===422)throw error;fail(app,422,'Conditional rules must contain valid JSON.')}}
async function audit(c,w,id,action,before,after){const json=value=>value?JSON.stringify(value,(key,item)=>key==='modifiedDate'||key==='updated_at'?undefined:item):null;await c.db('tbl_activity_log').insert({tenantId:c.tenantId,userId:c.userId,workflowId:w.id,entityType:'commercial_terms',entityId:id||null,actionType:action,summary:'Commercial/funding terms changed.',beforeJson:json(before),afterJson:json(after),createdDate:c.db.fn.now()})}
const childTables={price:'tbl_commercial_price_items',responsibility:'tbl_commercial_responsibility_items',adjustment:'tbl_commercial_adjustments',schedule:'tbl_commercial_payment_schedule'};
async function ensureSections(db,tenantId,workflowTypeId){const sections=[['agreement','Agreement',10,1],['prices','Price Items',20,1],['responsibilities','Responsibilities',30,1],['adjustments','Adjustments',40,1],['payment_terms','Payment / Settlement Terms',50,1],['payment_schedule','Payment Schedule',60,0],['additional','Additional Terms',70,1]];for(const [sectionKey,heading,sortOrder,isEnabled]of sections)await db('tbl_commercial_workflow_configs').insert({tenantId,workflowTypeId,sectionKey,heading,sortOrder,isEnabled}).onConflict(['tenantId','workflowTypeId','sectionKey']).ignore()}
module.exports={
 async get(){const c=await context(this),w=await workflow(c,this,this.req.query?.workflowId||this.req.query?.workflowid),typeId=w.workflowTypeId||0,sections=await c.db('tbl_commercial_workflow_configs').where({tenantId:c.tenantId,workflowTypeId:typeId,isEnabled:1}).orderBy('sortOrder'),options=await c.db('tbl_commercial_option_definitions').where({tenantId:c.tenantId,workflowTypeId:typeId,isActive:1}).orderBy('optionGroup').orderBy('sortOrder'),definitions=await c.db('tbl_commercial_item_definitions').where({tenantId:c.tenantId,workflowTypeId:typeId,isActive:1}).orderBy('sectionKey').orderBy('sortOrder'),record=await c.db('tbl_commercial_records as r').leftJoin('tbl_commercial_option_definitions as o','o.id','r.agreementTypeId').where({'r.tenantId':c.tenantId,'r.workflowId':w.id}).first('r.*','o.label as agreementTypeLabel','o.fieldRulesJson'),children={};for(const [key,table]of Object.entries(childTables)){let q=c.db(`${table} as x`);if(key==='responsibility')q=q.leftJoin('tbl_commercial_item_definitions as d','d.id','x.definitionId').leftJoin('tbl_commercial_option_definitions as o','o.id','x.responsibilityOptionId');children[key]=await q.where({'x.tenantId':c.tenantId,'x.workflowId':w.id,'x.isActive':1}).orderBy('x.sortOrder').select(key==='responsibility'?['x.*','d.label as definitionLabel','o.label as responsibilityLabel']:['x.*'])}const contract=await c.db('tbl_generated_contracts').where({tenantId:c.tenantId,workflowId:w.id}).orderBy('contractVersionNumber','desc').first('id','contractName','status','issuedDate','modifiedDate'),terms=await c.db('tbl_tenant_terminology').where({tenantId:c.tenantId}).whereIn('termKey',['commercial.tab_name','commercial.section_name','commercial.organisation','commercial.counterparty','commercial.price_items','commercial.responsibilities']).select('termKey','singularLabel');return{canEdit:await hasPermission(c.db,c.tenantId,c.userId,'commercial.edit')||await hasPermission(c.db,c.tenantId,c.userId,'commercial.manage'),canConfigure:await hasPermission(c.db,c.tenantId,c.userId,'commercial.configure'),workflowTypeId:typeId,sections,options,definitions,record:record||{currencyCode:(await c.db('tbl_tenants').where({id:c.tenantId}).first('defaultCurrency'))?.defaultCurrency||'GBP'},children,contract:contract||null,terminology:Object.fromEntries(terms.map(t=>[t.termKey,t.singularLabel]))}},
 async saveAgreement(){const c=await context(this,'commercial.edit'),w=await workflow(c,this,this.req.body?.workflowId),b=this.req.body||{},option=await c.db('tbl_commercial_option_definitions').where({id:Number(b.agreementTypeId)||0,tenantId:c.tenantId,workflowTypeId:w.workflowTypeId,optionGroup:'agreement_type',isActive:1}).first(),before=await c.db('tbl_commercial_records').where({tenantId:c.tenantId,workflowId:w.id}).first(),values={agreementTypeId:option?.id||null,currencyCode:String(b.currencyCode||'GBP').toUpperCase().slice(0,3),fixedAmount:num(b.fixedAmount),minimumAmount:num(b.minimumAmount),guaranteeAmount:num(b.guaranteeAmount),organisationPercentage:num(b.organisationPercentage,0,100),counterpartyPercentage:num(b.counterpartyPercentage,0,100),maximumAmount:num(b.maximumAmount),settlementBasis:String(b.settlementBasis||'').slice(0,500)||null,vatTreatment:String(b.vatTreatment||'').slice(0,120)||null,depositRequired:['1','true','on'].includes(String(b.depositRequired)),depositAmount:num(b.depositAmount),depositPercentage:num(b.depositPercentage,0,100),depositDueDate:b.depositDueDate||null,balanceDueDate:b.balanceDueDate||null,paymentTerms:String(b.paymentTerms||'').slice(0,500)||null,settlementPeriod:String(b.settlementPeriod||'').slice(0,160)||null,settlementMethod:String(b.settlementMethod||'').slice(0,160)||null,cancellationTerms:String(b.cancellationTerms||'')||null,notes:String(b.notes||'')||null,modifiedByUserId:c.userId,modifiedDate:c.db.fn.now()};if(option&&String(option.optionKey).includes('split')&&values.organisationPercentage!==null&&values.counterpartyPercentage!==null&&Math.abs(values.organisationPercentage+values.counterpartyPercentage-100)>.0001)fail(this,422,'The configured split percentages must total 100.');if(before)await c.db('tbl_commercial_records').where({id:before.id,tenantId:c.tenantId}).update(values);else{const ids=await c.db('tbl_commercial_records').insert({tenantId:c.tenantId,workflowId:w.id,createdByUserId:c.userId,...values});values.id=ids[0]}await audit(c,w,before?.id||values.id,'COMMERCIAL_TERMS_UPDATED',before,values);return{success:true}},
 async saveChild(){const c=await context(this,'commercial.edit'),w=await workflow(c,this,this.req.body?.workflowId),b=this.req.body||{},kind=String(b.kind||''),table=childTables[kind];if(!table)fail(this,422,'Unsupported commercial item type.');const id=Number(b.id)||0,before=id?await c.db(table).where({id,tenantId:c.tenantId,workflowId:w.id}).first():null;const common={sortOrder:Number(b.sortOrder)||100,isActive:1,modifiedByUserId:c.userId,modifiedDate:c.db.fn.now()};let values;if(kind==='price')values={description:String(b.description||'').trim().slice(0,160),amount:num(b.amount),quantity:num(b.quantity),vatTreatment:String(b.vatTreatment||'').slice(0,120)||null,notes:String(b.notes||'')||null};if(kind==='responsibility'){const def=await c.db('tbl_commercial_item_definitions').where({id:Number(b.definitionId)||0,tenantId:c.tenantId,workflowTypeId:w.workflowTypeId,isActive:1}).first(),opt=await c.db('tbl_commercial_option_definitions').where({id:Number(b.responsibilityOptionId)||0,tenantId:c.tenantId,workflowTypeId:w.workflowTypeId,optionGroup:'responsibility',isActive:1}).first();if(!def)fail(this,422,'Select a configured item.');values={definitionId:def.id,description:String(b.description||'').slice(0,160)||null,responsibilityOptionId:opt?.id||null,basis:String(b.basis||'').slice(0,80)||null,amount:def.allowAmount?num(b.amount):null,percentage:def.allowPercentage?num(b.percentage,0,100):null,quantity:def.allowQuantity?num(b.quantity):null,vatTreatment:def.allowVat?String(b.vatTreatment||'').slice(0,120)||null:null,settlementTreatment:String(b.settlementTreatment||'').slice(0,160)||null,notes:def.allowNotes?String(b.notes||'')||null:null}}if(kind==='adjustment')values={description:String(b.description||'').trim().slice(0,160),calculationType:['fixed','percentage','per_unit','included','manual'].includes(b.calculationType)?b.calculationType:'manual',amount:num(b.amount),percentage:num(b.percentage,0,100),unitAmount:num(b.unitAmount),notes:String(b.notes||'')||null};if(kind==='schedule')values={description:String(b.description||'').trim().slice(0,160),amount:num(b.amount),percentage:num(b.percentage,0,100),dueDate:b.dueDate||null,triggerText:String(b.triggerText||'').slice(0,255)||null,status:String(b.status||'planned').slice(0,40),notes:String(b.notes||'')||null};if(!values.description&&kind!=='responsibility')fail(this,422,'Description is required.');let savedId=id;if(before)await c.db(table).where({id,tenantId:c.tenantId,workflowId:w.id}).update({...values,...common});else{const ids=await c.db(table).insert({tenantId:c.tenantId,workflowId:w.id,createdByUserId:c.userId,...values,...common});savedId=ids[0]}await audit(c,w,savedId,'COMMERCIAL_ITEM_SAVED',before,{kind,...values});return{success:true,id:savedId}},
 async removeChild(){const c=await context(this,'commercial.edit'),w=await workflow(c,this,this.req.body?.workflowId),table=childTables[String(this.req.body?.kind||'')],id=Number(this.req.body?.id);if(!table)fail(this,422,'Unsupported commercial item type.');const before=await c.db(table).where({id,tenantId:c.tenantId,workflowId:w.id,isActive:1}).first();if(!before)fail(this,404,'Item not found.');await c.db(table).where({id,tenantId:c.tenantId,workflowId:w.id}).update({isActive:0,modifiedByUserId:c.userId,modifiedDate:c.db.fn.now()});await audit(c,w,id,'COMMERCIAL_ITEM_REMOVED',before,{isActive:0});return{success:true}},
 async ensureConfiguration(){const c=await context(this,'commercial.configure'),workflowTypeId=Number(this.req.body?.workflowTypeId),type=await c.db('tbl_workflow_types').where({id:workflowTypeId,tenantId:c.tenantId}).first();if(!type)fail(this,404,'Workflow type not found.');await ensureSections(c.db,c.tenantId,workflowTypeId);return{success:true}},
 async configuration(){const c=await context(this,'commercial.configure'),workflowTypeId=Number(this.req.query?.workflowTypeId||this.req.query?.workflowtypeid),type=await c.db('tbl_workflow_types').where({id:workflowTypeId,tenantId:c.tenantId}).first();if(!type)fail(this,404,'Workflow type not found.');await ensureSections(c.db,c.tenantId,workflowTypeId);return{workflowType:type,sections:await c.db('tbl_commercial_workflow_configs').where({tenantId:c.tenantId,workflowTypeId}).orderBy('sortOrder'),options:await c.db('tbl_commercial_option_definitions').where({tenantId:c.tenantId,workflowTypeId}).orderBy('optionGroup').orderBy('sortOrder'),definitions:await c.db('tbl_commercial_item_definitions').where({tenantId:c.tenantId,workflowTypeId}).orderBy('sectionKey').orderBy('sortOrder')}},
 async saveConfiguration(){
  const c=await context(this,'commercial.configure'),b=this.req.body||{},workflowTypeId=Number(b.workflowTypeId),type=await c.db('tbl_workflow_types').where({id:workflowTypeId,tenantId:c.tenantId}).first();
  if(!type)fail(this,404,'Workflow type not found.');
  const entity=String(b.entity||''),id=Number(b.id)||0;let table,values,unique;
  if(entity==='section'){
   table='tbl_commercial_workflow_configs';
   if(!['agreement','prices','responsibilities','adjustments','payment_terms','payment_schedule','additional'].includes(String(b.sectionKey)))fail(this,422,'Invalid section.');
   values={sectionKey:b.sectionKey,heading:String(b.label||'').trim().slice(0,160)||null,isEnabled:['1','true','on'].includes(String(b.isActive)),sortOrder:Number(b.sortOrder)||100};unique=['tenantId','workflowTypeId','sectionKey'];
  }else if(entity==='option'){
   table='tbl_commercial_option_definitions';
   if(!['agreement_type','responsibility'].includes(String(b.optionGroup)))fail(this,422,'Invalid option group.');
   values={optionGroup:b.optionGroup,optionKey:String(b.itemKey||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').slice(0,80),label:String(b.label||'').trim().slice(0,160),fieldRulesJson:rules(this,b.fieldRulesJson),sortOrder:Number(b.sortOrder)||100,isActive:['1','true','on'].includes(String(b.isActive))};unique=['tenantId','workflowTypeId','optionGroup','optionKey'];
  }else if(entity==='definition'){
   table='tbl_commercial_item_definitions';
   const defaultOptionKey=String(b.defaultOptionKey||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').slice(0,80)||null;
   if(defaultOptionKey&&!await c.db('tbl_commercial_option_definitions').where({tenantId:c.tenantId,workflowTypeId,optionGroup:'responsibility',optionKey:defaultOptionKey,isActive:1}).first())fail(this,422,'Default responsibility is not valid for this workflow type.');
   values={sectionKey:'responsibilities',itemKey:String(b.itemKey||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').slice(0,100),label:String(b.label||'').trim().slice(0,160),askResponsibility:['1','true','on'].includes(String(b.askResponsibility)),allowAmount:['1','true','on'].includes(String(b.allowAmount)),allowPercentage:['1','true','on'].includes(String(b.allowPercentage)),allowQuantity:['1','true','on'].includes(String(b.allowQuantity)),allowVat:['1','true','on'].includes(String(b.allowVat)),allowNotes:['1','true','on'].includes(String(b.allowNotes)),isRequired:['1','true','on'].includes(String(b.isRequired)),defaultOptionKey,sortOrder:Number(b.sortOrder)||100,isActive:['1','true','on'].includes(String(b.isActive))};unique=['tenantId','workflowTypeId','sectionKey','itemKey'];
  }else fail(this,422,'Unsupported configuration type.');
  if(!values.label&&entity!=='section')fail(this,422,'Label is required.');
  if(entity!=='section'&&!values[entity==='option'?'optionKey':'itemKey'])fail(this,422,'A stable key is required.');
  const before=id?await c.db(table).where({id,tenantId:c.tenantId,workflowTypeId}).first():null;
  if(before)await c.db(table).where({id,tenantId:c.tenantId,workflowTypeId}).update(values);else await c.db(table).insert({tenantId:c.tenantId,workflowTypeId,...values}).onConflict(unique).merge(values);
  await c.db('tbl_activity_log').insert({tenantId:c.tenantId,userId:c.userId,entityType:'commercial_configuration',entityId:workflowTypeId,actionType:'COMMERCIAL_CONFIGURATION_UPDATED',summary:`Commercial configuration updated for ${type.typeName}.`,beforeJson:before?JSON.stringify(before):null,afterJson:JSON.stringify({entity,...values}),createdDate:c.db.fn.now()});
  return{success:true};
 },
 _test:{num,childTables}
};
