const crypto = require('crypto');
const fs = require('fs-extra');
const path = require('path');
const { chromium } = require('playwright-core');

function safeFilename(value) {
    return String(value || 'contract')
        .normalize('NFKD')
        .replace(/[^\x00-\x7F]/g, '')
        .replace(/[^a-zA-Z0-9_-]+/g, '-')
        .replace(/^-+|-+$/g, '')
        .slice(0, 100) || 'contract';
}

function escapeHtml(value) {
    return String(value || '').replace(/[&<>"']/g, character => ({
        '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
    })[character]);
}

function browserExecutable() {
    const candidates = [
        process.env.CHROME_PATH,
        process.env.CHROMIUM_PATH,
        'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
        'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
        '/usr/bin/google-chrome',
        '/usr/bin/chromium',
        '/usr/bin/chromium-browser'
    ].filter(Boolean);
    return candidates.find(candidate => fs.existsSync(candidate));
}

function contractStorageRoot() {
    const configured = String(process.env.CONTRACT_STORAGE_PATH || '/uploads/contracts')
        .trim()
        .replace(/\\/g, '/')
        .replace(/\/+$/, '');
    if (!configured.startsWith('/') || configured.includes('..')) {
        throw new Error('CONTRACT_STORAGE_PATH must be a Wappler app path beginning with "/" and must not contain "..".');
    }
    return configured;
}

function contractDocument(title, bodyHtml) {
    return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title><style>
        @page{size:A4;margin:22mm 18mm 24mm}
        body{font-family:Arial,Helvetica,sans-serif;color:#20242a;font-size:10.5pt;line-height:1.5}
        h1{font-size:20pt;margin:0 0 18pt} h2{font-size:13pt;margin:18pt 0 7pt}
        table{width:100%;border-collapse:collapse} th,td{padding:6pt;border:1px solid #cfd4da;text-align:left;vertical-align:top}
        p{margin:0 0 9pt}.clause{break-inside:avoid}.footer{margin-top:24pt;border-top:1px solid #cfd4da;padding-top:8pt;color:#6c757d;font-size:8.5pt}
    </style></head><body>${bodyHtml || ''}<div class="footer">Generated by Meldren</div></body></html>`;
}

module.exports = {
    generate: async function (options) {
        let refererContractId;
        try {
            refererContractId = new URL(this.req.headers.referer).searchParams.get('id');
        } catch {
            refererContractId = undefined;
        }
        const contractId = Number(this.req.body?.contractId || this.req.query?.id || refererContractId);
        const tenantId = Number(this.req.session?.TENANT_ID);
        const userId = Number(this.req.session?.USER_ID);
        if (!Number.isInteger(contractId) || contractId <= 0) {
            throw new Error(`contractPdf.generate: contractId is required (url: ${this.req.originalUrl || 'unknown'}).`);
        }
        if (!Number.isInteger(tenantId) || tenantId <= 0) {
            throw new Error('contractPdf.generate: tenantId is required.');
        }
        if (!Number.isInteger(userId) || userId <= 0) {
            throw new Error('contractPdf.generate: userId is required.');
        }
        const db = this.getDbConnection('db');

        const contract = await db('tbl_generated_contracts as gc')
            .innerJoin('tbl_workflows as w', function () {
                this.on('w.id', 'gc.workflowId').andOn('w.tenantId', 'gc.tenantId');
            })
            .where('gc.id', contractId)
            .where('gc.tenantId', tenantId)
            .where('gc.status', 'draft')
            .whereExists(function () {
                this.select(db.raw('1'))
                    .from('tbl_tenant_modules as tm')
                    .innerJoin('tbl_modules as m', 'm.id', 'tm.moduleId')
                    .whereRaw('tm.tenantId = gc.tenantId')
                    .where('m.moduleCode', 'CONTRACT_GENERATION')
                    .where('m.isActive', 1)
                    .whereIn('tm.status', ['ACTIVE', 'TRIAL']);
            })
            .whereExists(function () {
                this.select(db.raw('1'))
                    .from('tbl_user_tenant_roles as utr')
                    .innerJoin('tbl_roles as r', 'r.id', 'utr.roleId')
                    .innerJoin('tbl_role_permissions as rp', 'rp.roleId', 'r.id')
                    .innerJoin('tbl_permissions as p', 'p.id', 'rp.permissionId')
                    .whereRaw('utr.userId = ?', [userId])
                    .whereRaw('utr.tenantId = gc.tenantId')
                    .where('utr.isActive', 1)
                    .where('r.isActive', 1)
                    .where('p.permissionCode', 'agreements.issue')
                    .where('p.isActive', 1);
            })
            .select('gc.id', 'gc.workflowId', 'gc.contractName', 'gc.renderedHtml', 'gc.templateVersionNumber', 'gc.contractVersionNumber')
            .first();

        if (!contract) throw new Error('The editable contract draft is unavailable.');

        const clauses = await db('tbl_contract_document_clauses')
            .where({ tenantId, contractId })
            .orderBy([{ column: 'displayOrder', order: 'asc' }, { column: 'id', order: 'asc' }])
            .select('sourceClauseId', 'clauseHeading', 'clauseTextSnapshot', 'clauseBehaviour', 'conditionKey', 'displayOrder', 'isIncluded', 'isCustom');

        const storageRoot = contractStorageRoot();
        const storageDirectory = `${storageRoot}/${tenantId}/${contract.workflowId}`;
        const absoluteDirectory = path.resolve(process.cwd(), '.' + storageDirectory);
        await fs.ensureDir(absoluteDirectory);

        const nextVersion = Number(contract.contractVersionNumber || 0) + 1;
        const filename = `${safeFilename(contract.contractName)}-v${nextVersion}-${contract.id}.pdf`;
        const absolutePath = path.join(absoluteDirectory, filename);
        const html = contractDocument(contract.contractName, contract.renderedHtml);

        const executablePath = browserExecutable();
        if (!executablePath) throw new Error('Chrome or Chromium is required to generate contract PDFs.');
        const browser = await chromium.launch({ executablePath, headless: true, args: ['--no-sandbox', '--disable-setuid-sandbox'] });
        try {
            const page = await browser.newPage();
            await page.setContent(html, { waitUntil: 'networkidle0' });
            await page.pdf({
                path: absolutePath,
                format: 'A4',
                printBackground: true,
                displayHeaderFooter: true,
                headerTemplate: '<div></div>',
                footerTemplate: `<div style="font:8px Arial;width:100%;padding:0 18mm;display:flex;justify-content:space-between;color:#777"><span>${escapeHtml(contract.contractName)} &middot; Version ${nextVersion}</span><span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span></div>`,
                margin: { top: '22mm', right: '18mm', bottom: '24mm', left: '18mm' }
            });
        } finally {
            await browser.close();
        }

        const file = await fs.readFile(absolutePath);
        const sha256 = crypto.createHash('sha256').update(file).digest('hex');
        const storagePath = storageDirectory + '/' + filename;

        const issuedDate = new Date();
        try {
            await db.transaction(async trx => {
                const updated = await trx('tbl_generated_contracts')
                    .where({ id: contractId, tenantId, status: 'draft', contractVersionNumber: contract.contractVersionNumber })
                    .update({
                        status: 'issued',
                        contractVersionNumber: nextVersion,
                        issuedByUserId: userId,
                        issuedDate,
                        pdfStoragePath: storagePath,
                        pdfFileName: filename,
                        pdfSha256: sha256,
                        pdfGeneratedDate: issuedDate,
                        modifiedByUserId: userId,
                        modifiedDate: issuedDate
                    });

                if (updated !== 1) throw new Error('The contract changed while it was being issued. Please review the latest draft.');

                await trx('tbl_contract_versions').insert({
                    tenantId,
                    contractId,
                    contractVersionNumber: nextVersion,
                    contractNameSnapshot: contract.contractName,
                    renderedHtmlSnapshot: contract.renderedHtml,
                    clausesJsonSnapshot: JSON.stringify(clauses),
                    pdfStoragePath: storagePath,
                    pdfFileName: filename,
                    pdfSha256: sha256,
                    issuedByUserId: userId,
                    issuedDate
                });
            });
        } catch (error) {
            await fs.remove(absolutePath);
            throw error;
        }

        return { success: true, contractId, contractVersionNumber: nextVersion, storagePath, filename, sha256, size: file.length };
    }
};
